"""add admin tables

Revision ID: 47b4659cb09e
Revises: 
Create Date: 2023-01-03 14:35:50.654512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b4659cb09e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=128), nullable=True),
    sa.Column('Password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('SanPhams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'LoaiSanPhams', ['MaLoaiSanPham'], ['MaLoaiSanPham'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SanPhams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'LoaiSanPhams', ['MaLoaiSanPham'], ['MaLoaiSanPham'])

    op.drop_table('admin')
    # ### end Alembic commands ###
