"""add username, password for customer

Revision ID: b6bca2a162cb
Revises: 
Create Date: 2023-01-01 17:32:03.025931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bca2a162cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KhachHangs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Username', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('Password', sa.String(length=128), nullable=True))

    with op.batch_alter_table('SanPhams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'LoaiSanPhams', ['MaLoaiSanPham'], ['MaLoaiSanPham'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SanPhams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'LoaiSanPhams', ['MaLoaiSanPham'], ['MaLoaiSanPham'])

    with op.batch_alter_table('KhachHangs', schema=None) as batch_op:
        batch_op.drop_column('Password')
        batch_op.drop_column('Username')

    # ### end Alembic commands ###
